apiVersion: v1
kind: Service
metadata:
 name: homeassistant
 namespace: homeassist
spec:
 ports:
   - port: 8123      
     targetPort: 8123    
 selector:
   app: homeassistant
 type: LoadBalancer   
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - image: homeassistant/home-assistant
          name: home-assistant
          volumeMounts:
            - name: config
              mountPath: "/config"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassist-pvc