apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassist-pvc
  namespace: homeassist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs