---
apiVersion: v1
kind: Service
metadata:
  name: nut-upsd
spec:
  ports:
  - { port: 3493, targetPort: 3493 }
  selector:
    name: nut-upsd
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nut-upsd
  name: nut-upsd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nut-upsd
  template:
    metadata:
      labels:
        name: nut-upsd
    spec:
      containers:
      - name: nut-upsd
        image: instantlinux/nut-upsd
        env:
        - name: SERIAL
          value: 0B2120N00200 
        securityContext:
          privileged: true
        #  temp overwrite entrypoint for troubleshooting
        # command: ["/bin/sh"]
        # args: ["-c", "sleep infinity"]
        volumeMounts:
        - name: usb
          mountPath: /dev/usb/hiddev0
        - name: secret
          mountPath: /run/secrets/nut-upsd-password
          readOnly: true
          subPath: nut-upsd-password
      serviceAccountName: nut-upsd-svcacct
      volumes:
      - name: usb
        hostPath: 
          path: /dev/usb/hiddev0 
      - name: secret
        secret:
          secretName: nut-upsd-password

