apiVersion: v1
kind: Service
metadata:
 name: homeassistant
 namespace: homeassist
spec:
 ports:
   - port: 8123      
     targetPort: 8123    
 selector:
   app: homeassistant
 type: LoadBalancer   
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: home-assistant
          image: debianha
          imagePullPolicy: IfNotPresent
          # volumeMounts:
          #   - name: config
          #     mountPath: "/config"
          command: ["/bin/sh", "-c"] 
          args: ["wget $(osagentlink); dpkg -i $(osagentinstall); while true; do sleep 30; done;" ]
          envFrom:
          - configMapRef:
              name:  haenvironment
      # volumes:
      #   - name: config
      #     persistentVolumeClaim:
      #       claimName: homeassist-pvc